name: quien_para
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"  # Updated for Flutter 3.29.0 compatibility
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0
  location: ^6.0.2
  geocoding: ^3.0.0
  http: ^1.2.2
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.2
  shared_preferences: ^2.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.3.0
  get_it: ^8.0.3
  firebase_storage: ^12.4.4
  connectivity_plus: ^6.1.3
  logger: ^2.5.0
  flutter_bloc: ^9.1.0
  confetti: ^0.8.0
  image_picker: ^1.1.2
  image: ^4.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  intl: ^0.20.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  bloc: ^9.0.0
  flutter_svg: ^2.0.17
  flutter_cache_manager: ^3.4.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0
  go_router: ^14.5.0
  badges: ^3.1.1
  provider: ^6.1.4
  crypto: ^3.0.6
  nested: ^1.0.0
  path: ^1.9.1
  cached_network_image: ^3.4.1
  firebase_core_platform_interface: ^5.4.0
  archive: ^4.0.7
  rxdart: ^0.28.0
  dartz: ^0.10.1
  uuid: ^4.5.1
  firebase_analytics: ^11.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Compatible with Flutter 3.29.0 and Dart 3.7
  build_runner: ^2.4.13
  freezed: ^2.4.5
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  bloc_test: ^10.0.0
  fake_cloud_firestore: ^3.1.0
  integration_test:
    sdk: flutter

  # The following section is specific to Flutter packages.
flutter:
  assets:
  - lib/assets/images/
  - lib/assets/fonts/
  - lib/assets/images/logo1.png

  uses-material-design: true

  fonts:
  - family: Playfair Display
    fonts:
    - asset: lib/assets/fonts/PlayfairDisplay-Regular.ttf
    - asset: lib/assets/fonts/PlayfairDisplay-Bold.ttf
      weight: 700
    - asset: lib/assets/fonts/PlayfairDisplay-Black.ttf
      weight: 900
    - asset: lib/assets/fonts/PlayfairDisplay-Italic.ttf
      style: italic
    - asset: lib/assets/fonts/PlayfairDisplay-BoldItalic.ttf
      style: italic
      weight: 700
  - family: Trajan Pro
    fonts:
    - asset: lib/assets/fonts/TrajanPro.ttf
    - asset: lib/assets/fonts/TrajanPro-Bold.otf
      weight: 700