// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA9CQ_w9JkSfkeKw-cyJir2Ck9wqRCbHgy',
    appId: '1:308528139700:web:2231ff2600f285ae3076e1',
    messagingSenderId: '308528139700',
    projectId: 'planing-931b8',
    authDomain: 'planing-931b8.firebaseapp.com',
    storageBucket: 'planing-931b8.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjrVZaO1N-wCKh1kzwUlpy-0TtMwEcQjg',
    appId: '1:308528139700:android:763a0f8069a954f33076e1',
    messagingSenderId: '308528139700',
    projectId: 'planing-931b8',
    storageBucket: 'planing-931b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjrVZaO1N-wCKh1kzwUlpy-0TtMwEcQjg',
    appId: '1:308528139700:ios:03b1297f58567d143076e1',
    messagingSenderId: '308528139700',
    projectId: 'planing-931b8',
    storageBucket: 'planing-931b8.appspot.com',
    iosBundleId: 'com.example.planing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjrVZaO1N-wCKh1kzwUlpy-0TtMwEcQjg',
    appId: '1:308528139700:ios:03b1297f58567d143076e1',
    messagingSenderId: '308528139700',
    projectId: 'planing-931b8',
    storageBucket: 'planing-931b8.appspot.com',
    iosBundleId: 'com.example.planing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA9CQ_w9JkSfkeKw-cyJir2Ck9wqRCbHgy',
    appId: '1:308528139700:web:4e1882ced82808433076e1',
    messagingSenderId: '308528139700',
    projectId: 'planing-931b8',
    authDomain: 'planing-931b8.firebaseapp.com',
    storageBucket: 'planing-931b8.appspot.com',
  );
}