// Mocks generated by Mockito 5.4.5 from annotations
// in quien_para/test/integration/component_interaction_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dartz/dartz.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i4;
import 'package:firebase_core/firebase_core.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:quien_para/domain/entities/failure.dart' as _i11;
import 'package:quien_para/domain/entities/plan/plan_entity.dart' as _i10;
import 'package:quien_para/domain/entities/plan/plan_with_creator_entity.dart'
    as _i9;
import 'package:quien_para/domain/failures/app_failures.dart' as _i8;
import 'package:quien_para/domain/repositories/plan/plan_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_1 extends _i1.SmartFake implements _i3.FirebaseApp {
  _FakeFirebaseApp_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActionCodeInfo_2 extends _i1.SmartFake
    implements _i4.ActionCodeInfo {
  _FakeActionCodeInfo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_3 extends _i1.SmartFake
    implements _i5.UserCredential {
  _FakeUserCredential_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_4 extends _i1.SmartFake
    implements _i5.ConfirmationResult {
  _FakeConfirmationResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserMetadata_5 extends _i1.SmartFake implements _i4.UserMetadata {
  _FakeUserMetadata_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_6 extends _i1.SmartFake implements _i5.MultiFactor {
  _FakeMultiFactor_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_7 extends _i1.SmartFake implements _i4.IdTokenResult {
  _FakeIdTokenResult_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_8 extends _i1.SmartFake implements _i5.User {
  _FakeUser_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlanRepository extends _i1.Mock implements _i6.PlanRepository {
  MockPlanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i2.Either<_i8.AppFailure, List<_i9.PlanWithCreatorEntity>>>
  getPlansWithCreators() =>
      (super.noSuchMethod(
            Invocation.method(#getPlansWithCreators, []),
            returnValue:
                _i7.Stream<
                  _i2.Either<_i8.AppFailure, List<_i9.PlanWithCreatorEntity>>
                >.empty(),
          )
          as _i7.Stream<
            _i2.Either<_i8.AppFailure, List<_i9.PlanWithCreatorEntity>>
          >);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>> matchPlan(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#matchPlan, [planId]),
            returnValue: _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>>.value(
              _FakeEither_0<_i8.AppFailure, _i2.Unit>(
                this,
                Invocation.method(#matchPlan, [planId]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>> unlikePlan(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#unlikePlan, [planId]),
            returnValue: _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>>.value(
              _FakeEither_0<_i8.AppFailure, _i2.Unit>(
                this,
                Invocation.method(#unlikePlan, [planId]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>
  getPlansByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlansByUserId, [userId]),
            returnValue:
                _i7.Future<
                  _i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>
                >.value(
                  _FakeEither_0<_i8.AppFailure, List<_i10.PlanEntity>>(
                    this,
                    Invocation.method(#getPlansByUserId, [userId]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>
  getParticipatingPlans(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getParticipatingPlans, [userId]),
            returnValue:
                _i7.Future<
                  _i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>
                >.value(
                  _FakeEither_0<_i8.AppFailure, List<_i10.PlanEntity>>(
                    this,
                    Invocation.method(#getParticipatingPlans, [userId]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>);

  @override
  _i7.Stream<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>
  getOtherUserPlansStream({required String? currentUserId, int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getOtherUserPlansStream, [], {
              #currentUserId: currentUserId,
              #limit: limit,
            }),
            returnValue:
                _i7.Stream<
                  _i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>
                >.empty(),
          )
          as _i7.Stream<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>> refreshOtherUserPlans({
    required String? currentUserId,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshOtherUserPlans, [], {
              #currentUserId: currentUserId,
              #limit: limit,
            }),
            returnValue: _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>>.value(
              _FakeEither_0<_i8.AppFailure, _i2.Unit>(
                this,
                Invocation.method(#refreshOtherUserPlans, [], {
                  #currentUserId: currentUserId,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>
  getPlansByCategory(String? category, {int? limit, String? lastDocumentId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPlansByCategory,
              [category],
              {#limit: limit, #lastDocumentId: lastDocumentId},
            ),
            returnValue:
                _i7.Future<
                  _i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>
                >.value(
                  _FakeEither_0<_i8.AppFailure, List<_i10.PlanEntity>>(
                    this,
                    Invocation.method(
                      #getPlansByCategory,
                      [category],
                      {#limit: limit, #lastDocumentId: lastDocumentId},
                    ),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>> getNearbyPlans({
    required double? latitude,
    required double? longitude,
    required double? radiusKm,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyPlans, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
              #limit: limit,
            }),
            returnValue:
                _i7.Future<
                  _i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>
                >.value(
                  _FakeEither_0<_i8.AppFailure, List<_i10.PlanEntity>>(
                    this,
                    Invocation.method(#getNearbyPlans, [], {
                      #latitude: latitude,
                      #longitude: longitude,
                      #radiusKm: radiusKm,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>
  getPopularPlans({int? limit, String? lastDocumentId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularPlans, [], {
              #limit: limit,
              #lastDocumentId: lastDocumentId,
            }),
            returnValue:
                _i7.Future<
                  _i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>
                >.value(
                  _FakeEither_0<_i8.AppFailure, List<_i10.PlanEntity>>(
                    this,
                    Invocation.method(#getPopularPlans, [], {
                      #limit: limit,
                      #lastDocumentId: lastDocumentId,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>
  getRecommendedPlans({required String? userId, int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendedPlans, [], {
              #userId: userId,
              #limit: limit,
            }),
            returnValue:
                _i7.Future<
                  _i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>
                >.value(
                  _FakeEither_0<_i8.AppFailure, List<_i10.PlanEntity>>(
                    this,
                    Invocation.method(#getRecommendedPlans, [], {
                      #userId: userId,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>
  searchPlansByText(String? searchText, {int? limit, String? lastDocumentId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchPlansByText,
              [searchText],
              {#limit: limit, #lastDocumentId: lastDocumentId},
            ),
            returnValue:
                _i7.Future<
                  _i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>
                >.value(
                  _FakeEither_0<_i8.AppFailure, List<_i10.PlanEntity>>(
                    this,
                    Invocation.method(
                      #searchPlansByText,
                      [searchText],
                      {#limit: limit, #lastDocumentId: lastDocumentId},
                    ),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>);

  @override
  _i7.Future<_i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>>
  searchPlans({
    required String? query,
    int? limit = 20,
    String? lastDocumentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPlans, [], {
              #query: query,
              #limit: limit,
              #lastDocumentId: lastDocumentId,
            }),
            returnValue:
                _i7.Future<
                  _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
                >.value(
                  _FakeEither_0<_i11.Failure, List<_i9.PlanWithCreatorEntity>>(
                    this,
                    Invocation.method(#searchPlans, [], {
                      #query: query,
                      #limit: limit,
                      #lastDocumentId: lastDocumentId,
                    }),
                  ),
                ),
          )
          as _i7.Future<
            _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
          >);

  @override
  _i7.Future<_i2.Either<_i11.Failure, List<String>>> getSearchSuggestions({
    required String? query,
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchSuggestions, [], {
              #query: query,
              #limit: limit,
            }),
            returnValue:
                _i7.Future<_i2.Either<_i11.Failure, List<String>>>.value(
                  _FakeEither_0<_i11.Failure, List<String>>(
                    this,
                    Invocation.method(#getSearchSuggestions, [], {
                      #query: query,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i11.Failure, List<String>>>);

  @override
  _i7.Future<_i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>>
  filterPlansByLocation({
    required double? latitude,
    required double? longitude,
    required double? radiusKm,
    int? limit = 20,
    String? lastDocumentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#filterPlansByLocation, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
              #limit: limit,
              #lastDocumentId: lastDocumentId,
            }),
            returnValue:
                _i7.Future<
                  _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
                >.value(
                  _FakeEither_0<_i11.Failure, List<_i9.PlanWithCreatorEntity>>(
                    this,
                    Invocation.method(#filterPlansByLocation, [], {
                      #latitude: latitude,
                      #longitude: longitude,
                      #radiusKm: radiusKm,
                      #limit: limit,
                      #lastDocumentId: lastDocumentId,
                    }),
                  ),
                ),
          )
          as _i7.Future<
            _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
          >);

  @override
  _i7.Future<_i2.Either<_i11.Failure, Map<String, dynamic>>> getCityCoordinates(
    String? cityName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCityCoordinates, [cityName]),
            returnValue:
                _i7.Future<
                  _i2.Either<_i11.Failure, Map<String, dynamic>>
                >.value(
                  _FakeEither_0<_i11.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#getCityCoordinates, [cityName]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i11.Failure, Map<String, dynamic>>>);

  @override
  _i7.Future<_i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>>
  filterPlansByDateRange({
    required DateTime? startDate,
    required DateTime? endDate,
    int? limit = 20,
    String? lastDocumentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#filterPlansByDateRange, [], {
              #startDate: startDate,
              #endDate: endDate,
              #limit: limit,
              #lastDocumentId: lastDocumentId,
            }),
            returnValue:
                _i7.Future<
                  _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
                >.value(
                  _FakeEither_0<_i11.Failure, List<_i9.PlanWithCreatorEntity>>(
                    this,
                    Invocation.method(#filterPlansByDateRange, [], {
                      #startDate: startDate,
                      #endDate: endDate,
                      #limit: limit,
                      #lastDocumentId: lastDocumentId,
                    }),
                  ),
                ),
          )
          as _i7.Future<
            _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
          >);

  @override
  _i7.Future<_i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>>
  filterPlansByCategory({
    required String? category,
    int? limit = 20,
    String? lastDocumentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#filterPlansByCategory, [], {
              #category: category,
              #limit: limit,
              #lastDocumentId: lastDocumentId,
            }),
            returnValue:
                _i7.Future<
                  _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
                >.value(
                  _FakeEither_0<_i11.Failure, List<_i9.PlanWithCreatorEntity>>(
                    this,
                    Invocation.method(#filterPlansByCategory, [], {
                      #category: category,
                      #limit: limit,
                      #lastDocumentId: lastDocumentId,
                    }),
                  ),
                ),
          )
          as _i7.Future<
            _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
          >);

  @override
  _i7.Future<_i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>>
  filterPlansByMultipleCategories({
    required List<String>? categories,
    int? limit = 20,
    String? lastDocumentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#filterPlansByMultipleCategories, [], {
              #categories: categories,
              #limit: limit,
              #lastDocumentId: lastDocumentId,
            }),
            returnValue:
                _i7.Future<
                  _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
                >.value(
                  _FakeEither_0<_i11.Failure, List<_i9.PlanWithCreatorEntity>>(
                    this,
                    Invocation.method(#filterPlansByMultipleCategories, [], {
                      #categories: categories,
                      #limit: limit,
                      #lastDocumentId: lastDocumentId,
                    }),
                  ),
                ),
          )
          as _i7.Future<
            _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
          >);

  @override
  _i7.Future<_i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>>
  getPopularPlansByCategory({required String? category, int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularPlansByCategory, [], {
              #category: category,
              #limit: limit,
            }),
            returnValue:
                _i7.Future<
                  _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
                >.value(
                  _FakeEither_0<_i11.Failure, List<_i9.PlanWithCreatorEntity>>(
                    this,
                    Invocation.method(#getPopularPlansByCategory, [], {
                      #category: category,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i7.Future<
            _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
          >);

  @override
  _i7.Future<_i2.Either<_i11.Failure, List<String>>> getSuggestedCategories({
    required String? userId,
    int? limit = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedCategories, [], {
              #userId: userId,
              #limit: limit,
            }),
            returnValue:
                _i7.Future<_i2.Either<_i11.Failure, List<String>>>.value(
                  _FakeEither_0<_i11.Failure, List<String>>(
                    this,
                    Invocation.method(#getSuggestedCategories, [], {
                      #userId: userId,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i11.Failure, List<String>>>);

  @override
  _i7.Future<_i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>>
  searchPlansAdvanced({
    String? query,
    String? category,
    double? latitude,
    double? longitude,
    double? radiusKm,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 20,
    String? lastDocumentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPlansAdvanced, [], {
              #query: query,
              #category: category,
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
              #startDate: startDate,
              #endDate: endDate,
              #limit: limit,
              #lastDocumentId: lastDocumentId,
            }),
            returnValue:
                _i7.Future<
                  _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
                >.value(
                  _FakeEither_0<_i11.Failure, List<_i9.PlanWithCreatorEntity>>(
                    this,
                    Invocation.method(#searchPlansAdvanced, [], {
                      #query: query,
                      #category: category,
                      #latitude: latitude,
                      #longitude: longitude,
                      #radiusKm: radiusKm,
                      #startDate: startDate,
                      #endDate: endDate,
                      #limit: limit,
                      #lastDocumentId: lastDocumentId,
                    }),
                  ),
                ),
          )
          as _i7.Future<
            _i2.Either<_i11.Failure, List<_i9.PlanWithCreatorEntity>>
          >);

  @override
  _i7.Future<_i2.Either<_i11.Failure, _i2.Unit>> saveSearchToHistory({
    required String? userId,
    required String? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveSearchToHistory, [], {
              #userId: userId,
              #query: query,
            }),
            returnValue: _i7.Future<_i2.Either<_i11.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i11.Failure, _i2.Unit>(
                this,
                Invocation.method(#saveSearchToHistory, [], {
                  #userId: userId,
                  #query: query,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i11.Failure, _i2.Unit>>);

  @override
  _i7.Future<_i2.Either<_i11.Failure, List<String>>> getSearchHistory({
    required String? userId,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchHistory, [], {
              #userId: userId,
              #limit: limit,
            }),
            returnValue:
                _i7.Future<_i2.Either<_i11.Failure, List<String>>>.value(
                  _FakeEither_0<_i11.Failure, List<String>>(
                    this,
                    Invocation.method(#getSearchHistory, [], {
                      #userId: userId,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i11.Failure, List<String>>>);

  @override
  _i7.Future<_i2.Either<_i11.Failure, _i2.Unit>> clearSearchHistory({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clearSearchHistory, [], {#userId: userId}),
            returnValue: _i7.Future<_i2.Either<_i11.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i11.Failure, _i2.Unit>(
                this,
                Invocation.method(#clearSearchHistory, [], {#userId: userId}),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i11.Failure, _i2.Unit>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity?>> getById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity?>>.value(
                  _FakeEither_0<_i8.AppFailure, _i10.PlanEntity?>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity?>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>> getAll({
    int? limit,
    String? lastDocumentId,
    Map<String, dynamic>? filters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #limit: limit,
              #lastDocumentId: lastDocumentId,
              #filters: filters,
            }),
            returnValue:
                _i7.Future<
                  _i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>
                >.value(
                  _FakeEither_0<_i8.AppFailure, List<_i10.PlanEntity>>(
                    this,
                    Invocation.method(#getAll, [], {
                      #limit: limit,
                      #lastDocumentId: lastDocumentId,
                      #filters: filters,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity>> create(
    _i10.PlanEntity? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue:
                _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity>>.value(
                  _FakeEither_0<_i8.AppFailure, _i10.PlanEntity>(
                    this,
                    Invocation.method(#create, [entity]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity>> update(
    _i10.PlanEntity? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity]),
            returnValue:
                _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity>>.value(
                  _FakeEither_0<_i8.AppFailure, _i10.PlanEntity>(
                    this,
                    Invocation.method(#update, [entity]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>>.value(
              _FakeEither_0<_i8.AppFailure, _i2.Unit>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>> search(
    Map<String, dynamic>? criteria, {
    int? limit,
    String? lastDocumentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [criteria],
              {#limit: limit, #lastDocumentId: lastDocumentId},
            ),
            returnValue:
                _i7.Future<
                  _i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>
                >.value(
                  _FakeEither_0<_i8.AppFailure, List<_i10.PlanEntity>>(
                    this,
                    Invocation.method(
                      #search,
                      [criteria],
                      {#limit: limit, #lastDocumentId: lastDocumentId},
                    ),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, bool>> exists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [id]),
            returnValue: _i7.Future<_i2.Either<_i8.AppFailure, bool>>.value(
              _FakeEither_0<_i8.AppFailure, bool>(
                this,
                Invocation.method(#exists, [id]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, bool>>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>> invalidateCache() =>
      (super.noSuchMethod(
            Invocation.method(#invalidateCache, []),
            returnValue: _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>>.value(
              _FakeEither_0<_i8.AppFailure, _i2.Unit>(
                this,
                Invocation.method(#invalidateCache, []),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, _i2.Unit>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity?>> refresh(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity?>>.value(
                  _FakeEither_0<_i8.AppFailure, _i10.PlanEntity?>(
                    this,
                    Invocation.method(#refresh, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, _i10.PlanEntity?>>);

  @override
  _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>> refreshAll({
    Map<String, dynamic>? filters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshAll, [], {#filters: filters}),
            returnValue:
                _i7.Future<
                  _i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>
                >.value(
                  _FakeEither_0<_i8.AppFailure, List<_i10.PlanEntity>>(
                    this,
                    Invocation.method(#refreshAll, [], {#filters: filters}),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.AppFailure, List<_i10.PlanEntity>>>);
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i5.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_1(this, Invocation.getter(#app)),
          )
          as _i3.FirebaseApp);

  @override
  set app(_i3.FirebaseApp? _app) => super.noSuchMethod(
    Invocation.setter(#app, _app),
    returnValueForMissingStub: null,
  );

  @override
  set tenantId(String? tenantId) => super.noSuchMethod(
    Invocation.setter(#tenantId, tenantId),
    returnValueForMissingStub: null,
  );

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
    Invocation.setter(#customAuthDomain, customAuthDomain),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i7.Future<void> useAuthEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #useAuthEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> applyActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#applyActionCode, [code]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#checkActionCode, [code]),
            returnValue: _i7.Future<_i4.ActionCodeInfo>.value(
              _FakeActionCodeInfo_2(
                this,
                Invocation.method(#checkActionCode, [code]),
              ),
            ),
          )
          as _i7.Future<_i4.ActionCodeInfo>);

  @override
  _i7.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<List<String>> fetchSignInMethodsForEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSignInMethodsForEmail, [email]),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<_i5.UserCredential> getRedirectResult() =>
      (super.noSuchMethod(
            Invocation.method(#getRedirectResult, []),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#getRedirectResult, []),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) =>
      (super.noSuchMethod(
            Invocation.method(#isSignInWithEmailLink, [emailLink]),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Stream<_i5.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i7.Stream<_i5.User?>.empty(),
          )
          as _i7.Stream<_i5.User?>);

  @override
  _i7.Stream<_i5.User?> idTokenChanges() =>
      (super.noSuchMethod(
            Invocation.method(#idTokenChanges, []),
            returnValue: _i7.Stream<_i5.User?>.empty(),
          )
          as _i7.Stream<_i5.User?>);

  @override
  _i7.Stream<_i5.User?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i7.Stream<_i5.User?>.empty(),
          )
          as _i7.Stream<_i5.User?>);

  @override
  _i7.Future<void> sendPasswordResetEmail({
    required String? email,
    _i4.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i4.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignInLinkToEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSettings, [], {
              #appVerificationDisabledForTesting:
                  appVerificationDisabledForTesting,
              #userAccessGroup: userAccessGroup,
              #phoneNumber: phoneNumber,
              #smsCode: smsCode,
              #forceRecaptchaFlow: forceRecaptchaFlow,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setPersistence(_i4.Persistence? persistence) =>
      (super.noSuchMethod(
            Invocation.method(#setPersistence, [persistence]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.UserCredential> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.UserCredential> signInWithCredential(
    _i4.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredential, [credential]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#signInWithCredential, [credential]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCustomToken, [token]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#signInWithCustomToken, [token]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailLink, [], {
              #email: email,
              #emailLink: emailLink,
            }),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#signInWithEmailLink, [], {
                  #email: email,
                  #emailLink: emailLink,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.UserCredential> signInWithProvider(
    _i4.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithProvider, [provider]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#signInWithProvider, [provider]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i5.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i7.Future<_i5.ConfirmationResult>.value(
              _FakeConfirmationResult_4(
                this,
                Invocation.method(#signInWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i7.Future<_i5.ConfirmationResult>);

  @override
  _i7.Future<_i5.UserCredential> signInWithPopup(_i4.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPopup, [provider]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#signInWithPopup, [provider]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<void> signInWithRedirect(_i4.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithRedirect, [provider]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetCode, [code]),
            returnValue: _i7.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#verifyPasswordResetCode, [code]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i4.PhoneMultiFactorInfo? multiFactorInfo,
    required _i4.PhoneVerificationCompleted? verificationCompleted,
    required _i4.PhoneVerificationFailed? verificationFailed,
    required _i4.PhoneCodeSent? codeSent,
    required _i4.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i4.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumber, [], {
              #phoneNumber: phoneNumber,
              #multiFactorInfo: multiFactorInfo,
              #verificationCompleted: verificationCompleted,
              #verificationFailed: verificationFailed,
              #codeSent: codeSent,
              #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
              #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
              #timeout: timeout,
              #forceResendingToken: forceResendingToken,
              #multiFactorSession: multiFactorSession,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> revokeTokenWithAuthorizationCode(
    String? authorizationCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#revokeTokenWithAuthorizationCode, [
              authorizationCode,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i5.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  _i4.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_5(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i4.UserMetadata);

  @override
  List<_i4.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i4.UserInfo>[],
          )
          as List<_i4.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i12.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  _i5.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_6(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i5.MultiFactor);

  @override
  _i7.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<_i4.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i7.Future<_i4.IdTokenResult>.value(
              _FakeIdTokenResult_7(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i7.Future<_i4.IdTokenResult>);

  @override
  _i7.Future<_i5.UserCredential> linkWithCredential(
    _i4.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.UserCredential> linkWithProvider(_i4.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.UserCredential> reauthenticateWithProvider(
    _i4.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<_i5.UserCredential> reauthenticateWithPopup(
    _i4.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<void> reauthenticateWithRedirect(_i4.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.UserCredential> linkWithPopup(_i4.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<void> linkWithRedirect(_i4.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i5.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i7.Future<_i5.ConfirmationResult>.value(
              _FakeConfirmationResult_4(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i7.Future<_i5.ConfirmationResult>);

  @override
  _i7.Future<_i5.UserCredential> reauthenticateWithCredential(
    _i4.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i7.Future<_i5.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i7.Future<_i5.UserCredential>);

  @override
  _i7.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> sendEmailVerification([
    _i4.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i7.Future<_i5.User>.value(
              _FakeUser_8(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i7.Future<_i5.User>);

  @override
  _i7.Future<void> updateEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [newEmail]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updatePhoneNumber(
    _i4.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i4.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
